apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
spec:
  scope: Namespaced
  group: otus.homework
  names:
    kind: MySQL
    shortNames:
      - my
    singular: mysql
    plural: mysqls
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                  pattern: ^.+\:.+$
                database:
                  type: string
                password:
                  type: string
                  minLength: 8
                storage_size:
                  type: string
                  default: "1Gi"
                  pattern: ^[0-9]+(Gi|Mi)$
              required:
                  - database
                  - password
                  - image
            status:
              type: object
              properties:
                phase:
                  type: string
                message:
                  type: string
                ready:
                  type: boolean