apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homework-ingress
  namespace: homework
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /index.html
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: "nginx"
  rules:
    - host: homework.otus
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homework-service
                port:
                  number: 8000
          # - path: /homepage(/|$)(.*)
          #   pathType: ImplementationSpecific
          #   backend:
          #     service:
          #       name: homework-service
          #       port:
          #         number: 8000
          # - path: /homepage
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: homework-service
          #       port:
          #         number: 8000