apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter-service
  namespace: nginx-mon
  labels:
    app: nginx-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  selector:
    app: nginx-exporter
  ports:
  - port: 9113
    targetPort: 9113
  type: ClusterIP