apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: default
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy:  Retain
  storageClassName: local-storage
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: pvc
          operator: In
          values:
            - local
